using Rawaj.Domain.Entities.Campaigns;
using Rawaj.Domain.Enums;
using Rawaj.Domain.ValueObjects;
using Rawaj.Domain.ValueObjects.CampaignBriefs;

namespace Rawaj.Application.Features.Campaigns.Common;

public record CampaignResponse(
    Guid Id,
    Guid BrandProfileId,
    string CampaignType,
    int CurrentStep,
    bool IsOnboardingComplete,
    DateTime? OnboardingCompletedAt,
    string? Name,
    string? Objective,
    List<string> TargetPlatforms,
    DateOnly? CampaignStartDate,
    DateOnly? EndDate,
    string? CampaignGoal,
    string? CampaignDuration,
    string? CampaignOutcome,
    CampaignBrief? CampaignBrief,
    string? BrandName,
    string? Tagline,
    string? InstagramHandle,
    string? Website,
    string? Sector,
    string? Location,
    string? BusinessAge,
    string? Stage,
    List<string>? BrandWords,
    List<string>? BrandTone,
    string? HasBrandGuidelines,
    string? GuidelinesFileUrl,
    List<string>? BrandColors,
    string? LogoFileUrl,
    List<string>? ContentLanguages,
    string? ProductDescription,
    string? UniqueValueProposition,
    string? PricePositioning,
    string? StorePresence,
    List<string>? ExistingPlatforms,
    string? AudienceGender,
    string? CustomerType,
    List<string>? AgeRanges,
    List<string>? IncomeLevel,
    string? CustomerLocation,
    string? EducationLevel,
    string? TargetDescription,
    List<string>? Interests,
    string? PainPoints,
    List<string>? BuyingBehavior,
    string? HasExistingCustomers,
    List<string>? AudiencePlatforms,
    string? PositioningVs,
    List<string>? SuccessMetrics,
    List<string>? BrandsAdmired,
    string? MonthlyBudget,
    decimal? BudgetFrom,
    decimal? BudgetTo,
    List<string>? PlatformRanking,
    List<string>? Goals,
    string? Timeframe,
    string? AgencyExperience,
    string? TargetSales,
    List<string>? CampaignPhotoUrls,
    string? Hashtags,
    string? AdditionalNotes,
    bool? FacebookConnected,
    string? FacebookAccountName,
    bool? InstagramConnected,
    string? InstagramAccountName,
    List<StrategistQA>? StrategistAnswers,
    CampaignStatus Status,
    DateTime CreatedAt,
    DateTime UpdatedAt)
{
    public static CampaignResponse FromEntity(MarketingCampaign c) => new(
        c.Id,
        c.BrandProfileId,
        c.CampaignType,
        c.CurrentStep,
        c.IsOnboardingComplete,
        c.OnboardingCompletedAt,
        c.Name,
        c.Objective,
        c.TargetPlatforms,
        c.StartDate,
        c.EndDate,
        c.CampaignGoal,
        c.CampaignDuration,
        c.CampaignOutcome,
        c.CampaignBrief,
        c.BrandName,
        c.Tagline,
        c.InstagramHandle,
        c.Website,
        c.Sector,
        c.Location,
        c.BusinessAge,
        c.Stage,
        c.BrandWords,
        c.BrandTone,
        c.HasBrandGuidelines,
        c.GuidelinesFileUrl,
        c.BrandColors,
        c.LogoFileUrl,
        c.ContentLanguages,
        c.ProductDescription,
        c.UniqueValueProposition,
        c.PricePositioning,
        c.StorePresence,
        c.ExistingPlatforms,
        c.AudienceGender,
        c.CustomerType,
        c.AgeRanges,
        c.IncomeLevel,
        c.CustomerLocation,
        c.EducationLevel,
        c.TargetDescription,
        c.Interests,
        c.PainPoints,
        c.BuyingBehavior,
        c.HasExistingCustomers,
        c.AudiencePlatforms,
        c.PositioningVs,
        c.SuccessMetrics,
        c.BrandsAdmired,
        c.MonthlyBudget,
        c.BudgetFrom,
        c.BudgetTo,
        c.PlatformRanking,
        c.Goals,
        c.Timeframe,
        c.AgencyExperience,
        c.TargetSales,
        c.CampaignPhotoUrls,
        c.Hashtags,
        c.AdditionalNotes,
        c.FacebookConnected,
        c.FacebookAccountName,
        c.InstagramConnected,
        c.InstagramAccountName,
        c.StrategistAnswers,
        c.Status,
        c.CreatedAt,
        c.UpdatedAt);
}
